name: Build and push the tagged build to production

on:
  push:
    branches: [ main1 ]
    
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

        # step 3: Build Docker Image  
      - name: Build Docker
        run: docker build . -t ${{ secrets.ACR_NAME}}/myimage1:${GITHUB_REF#refs/tags}
        
        # step 4: Push Docker to Azure Registry  
      - name: Push Docker
        run: docker push ${{ secrets.ACR_NAME}}/myimage1:${GITHUB_REF#refs/tags}
